FROM nginx
COPY conf/common.conf /etc/nginx/common.conf
COPY conf/common_location.conf /etc/nginx/common_location.conf
COPY conf/ssl.conf /etc/nginx/ssl.conf
COPY conf/bbb.conf /etc/nginx/conf.d/bbb.conf
EXPOSE 80 443
