export const MT = {
    SET_FROM_EMAIL: "SET_FROM_EMAIL",
    SET_FROM_NAME: "SET_FROM_NAME",
    SET_TO_NAME : "SET_TO_NAME",
    SET_IMAGE: "SET_IMAGE",
    SET_STORY: "SET_STORY",
    SET_GTC: "SET_GTC",
    SET_POSTINGS: "SET_POSTINGS",
    SUBMIT: "SUBMIT",
    RESET: "RESET"
}
